# Generated by Django 5.0.3 on 2024-04-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_one', '0002_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
